import test from 'node:test';
import assert from 'node:assert/strict';
import { decodeState, encodeState, emptyState } from '../../js/storage.js';
const ids=new Set(['a','b']);
test('state export import roundtrip is versioned',()=>{const state={version:1,favorites:['a'],rides:[{routeId:'a',date:'2026-07-18',note:'gut'}]};assert.deepEqual(decodeState(encodeState(state),ids),state)});
test('unknown route id rejects the whole import',()=>assert.throws(()=>decodeState(JSON.stringify({version:1,favorites:['x'],rides:[]}),ids),/STATE_ROUTE_UNKNOWN/));
test('prototype and additional fields are rejected',()=>assert.throws(()=>decodeState('{"version":1,"favorites":[],"rides":[],"__proto__":{}}',ids),/STATE_SCHEMA_INVALID/));
test('broken state falls back only through explicit helper',()=>assert.deepEqual(emptyState(),{version:1,favorites:[],rides:[]}));
test('limits are enforced',()=>{assert.throws(()=>decodeState(JSON.stringify({version:1,favorites:Array.from({length:101},(_,i)=>String(i)),rides:[]}),new Set(Array.from({length:101},(_,i)=>String(i)))),/STATE_FAVORITES_LIMIT/);assert.throws(()=>decodeState(JSON.stringify({version:1,favorites:[],rides:[{routeId:'a',date:'2026-01-01',note:'x'.repeat(513)}]}),ids),/STATE_STRING_LIMIT/)});
test('impossible calendar dates are rejected',()=>{for(const date of ['2026-99-99','2026-02-30','2025-02-29'])assert.throws(()=>decodeState(JSON.stringify({version:1,favorites:[],rides:[{routeId:'a',date,note:''}]}),ids),/STATE_DATE_INVALID/);assert.equal(decodeState(JSON.stringify({version:1,favorites:[],rides:[{routeId:'a',date:'2024-02-29',note:''}]}),ids).rides[0].date,'2024-02-29');});
