const LABELS={scenery:'Natur',trail:'Trail',low_traffic:'wenig Verkehr',emtb_fun:'E-MTB Spaß',viewpoints:'Aussicht',loop_quality:'Rundkurs',surface_confidence:'Daten'};
const $=id=>document.getElementById(id);let DATA=[],MODEL={},WEATHER=null,LOGS=[];
const q=$('q'),sort=$('sort'),type=$('type'),start=$('start'),grid=$('grid'),summary=$('summary'),rec=$('recommendation'),batteryLeft=$('batteryLeft'),batteryLeftText=$('batteryLeftText'),assist=$('assist');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(n){return Math.max(0,Math.min(100,Math.round(n)))}
function today(){return new Date().toISOString().slice(0,10)}
function mudScore(){if(!WEATHER)return {score:60,label:'Wetter lädt',cls:'warn'};const rain=WEATHER.rain48,temp=WEATHER.temp,wind=WEATHER.wind;let score=100-rain*9-Math.max(0,wind-25)*1.3+(temp<4?-12:0);score=pct(score);let label=score>75?'trocken/gut':score>55?'fahrbar mit Vorsicht':score>35?'matschig – Schotter bevorzugen':'Trail meiden';return {score,label,cls:score>75?'good':score>55?'warn':'bad'}}
async function loadWeather(){try{const url='https://api.open-meteo.com/v1/forecast?latitude=52.1224&longitude=9.3448&hourly=rain&current=temperature_2m,wind_speed_10m&past_days=2&forecast_days=2&timezone=Europe%2FBerlin';const j=await fetch(url).then(r=>r.json());const rain=(j.hourly?.rain||[]).slice(0,48).reduce((a,b)=>a+(Number(b)||0),0);WEATHER={rain48:Math.round(rain*10)/10,temp:Math.round(j.current?.temperature_2m??0),wind:Math.round(j.current?.wind_speed_10m??0)};$('weatherPill').innerHTML=`Wetter: <strong>${WEATHER.temp}°C · ${WEATHER.rain48} mm/48h · ${WEATHER.wind} km/h</strong>`}catch(e){WEATHER={rain48:0,temp:12,wind:10,offline:true};$('weatherPill').innerHTML='Wetter: <strong>offline, neutral gerechnet</strong>'}render()}
function populate(){type.innerHTML='<option value="">Alle Typen</option>'+[...new Set(DATA.map(r=>r.type))].sort().map(t=>`<option>${esc(t)}</option>`).join('');start.innerHTML='<option value="">Alle Starts</option>'+[...new Set(DATA.map(r=>r.start_mode))].sort().map(t=>`<option>${esc(t)}</option>`).join('');$('logRoute').innerHTML=DATA.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('');$('logDate').value=today()}
function batteryStatus(r){const need=r.battery_model?.[assist.value]||50,left=Number(batteryLeft.value),reserve=r.battery_model?.reserve_percent||15,margin=left-need-reserve;return {need,left,margin,label:margin>=20?'locker':margin>=5?'passt knapp':margin>=0?'Reserve dünn':'zu knapp',cls:margin>=20?'good':margin>=0?'warn':'bad'}}
function smartScore(r){const m=mudScore().score;const b=batteryStatus(r);let s=r.score + (m-60)*0.18 + Math.min(12,Math.max(-22,b.margin*0.45));if(r.type.includes('Feierabend'))s+=3;return Math.round(s*10)/10}
function rows(){let rows=[...DATA];const query=q.value.toLowerCase();if(query)rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query));if(type.value)rows=rows.filter(r=>r.type===type.value);if(start.value)rows=rows.filter(r=>r.start_mode===start.value);const key=sort.value;rows.sort((a,b)=>key==='smart'?smartScore(b)-smartScore(a):key==='difficulty'?String(a[key]).localeCompare(String(b[key])):(b[key]||0)-(a[key]||0));return rows}
function renderSummary(rs){const top=rs[0],m=mudScore();summary.innerHTML=`<div class="summary-card"><b>${rs.length}</b><span>Routen</span></div><div class="summary-card"><b>${top?esc(top.name):'–'}</b><span>Top jetzt</span></div><div class="summary-card ${m.cls}"><b>${m.score}/100</b><span>Matschscore · ${esc(m.label)}</span></div><div class="summary-card"><b>${batteryLeft.value}% · ${esc(assist.value)}</b><span>Akku-Modell</span></div>`}
function miniMap(id){return `<svg class="map" viewBox="0 0 100 62" data-track="${esc(id)}"><polyline points=""/><circle cx="0" cy="0" r="2"/><circle cx="100" cy="62" r="2"/></svg>`}
function renderRecommendation(rs){const r=rs[0],m=mudScore();if(!r){rec.innerHTML='';return}const b=batteryStatus(r);rec.innerHTML=`<div><h2>Wochenend-Empfehlung: ${esc(r.name)}</h2><p>Smartscore ${smartScore(r)} · Wetter/Matsch: ${m.score}/100 (${esc(m.label)}) · Akku ${b.label} (${b.need}% Bedarf + Reserve).</p></div><div class="actions"><a href="#${esc(r.id)}">Route ansehen</a><a href="${esc(r.gpx_file)}" download>GPX laden</a><a href="${esc(r.planner_link)}" target="_blank" rel="noopener">BRouter öffnen</a></div>`}
function render(){batteryLeftText.textContent=batteryLeft.value+'%';const rs=rows();renderSummary(rs);renderRecommendation(rs);grid.innerHTML=rs.map(r=>{const b=batteryStatus(r),m=mudScore();return `<article class="card" id="${esc(r.id)}"><div class="top"><div><h2>${esc(r.name)}</h2><div class="meta">${esc(r.region)} · ${esc(r.type)} · ${esc(r.start_mode)}</div></div><div class="score">${smartScore(r)}</div></div>${miniMap(r.id)}<div class="stats"><div class="stat"><b>${r.distance_km} km</b><span>Distanz</span></div><div class="stat"><b>${r.elevation_m} hm</b><span>Höhenmeter</span></div><div class="stat"><b>${esc(r.duration)}</b><span>Zeit</span></div><div class="stat ${b.cls}"><b>${b.need}%</b><span>Akku: ${esc(b.label)}</span></div><div class="stat ${m.cls}"><b>${m.score}/100</b><span>Matsch</span></div><div class="stat"><b>${r.track_points||'–'}</b><span>Trackpunkte</span></div></div><p>${esc(r.best_for)}</p><div class="tagrow">${r.highlights.map(h=>`<span class="tag">${esc(h)}</span>`).join('')}</div><p class="meta"><b>Track:</b> ${esc(r.track_source)} · <b>Untergrund:</b> ${esc(r.surface)}</p><p class="warn"><b>Check:</b> ${esc(r.risk_notes.join(' · '))}</p><div class="links"><a href="${esc(r.komoot_link)}" target="_blank" rel="noopener">Komoot</a><a href="${esc(r.navigation_link)}" target="_blank" rel="noopener">Navigation</a><a href="${esc(r.planner_link)}" target="_blank" rel="noopener">Planen</a><a href="${esc(r.gpx_file)}" download>GPX</a><a href="${esc(r.track_geojson_file||'routes.json')}" target="_blank" rel="noopener">GeoJSON</a></div><details><summary>Score, Akku & nächste Schritte</summary><p>${esc(r.maturity)}</p><p>${esc(r.battery_model?.note||'')}</p><ul>${r.next_actions.map(a=>`<li>${esc(a)}</li>`).join('')}</ul><div class="scorebars">${Object.entries(r.scores).map(([k,v])=>`<div class="scorebar"><span>${LABELS[k]||k}</span><div class="track"><div class="fill w${pct(v)}"></div></div><b>${v}</b></div>`).join('')}</div></details></article>`}).join('');hydrateMaps()}
async function hydrateMaps(){for(const svg of document.querySelectorAll('svg.map')){const id=svg.dataset.track;const r=DATA.find(x=>x.id===id);if(!r?.track_geojson_file)continue;try{const gj=await fetch(r.track_geojson_file).then(x=>x.json());const pts=gj.features[0].geometry.coordinates.map(c=>[c[0],c[1]]);const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys);const s=pts.map(([x,y])=>`${((x-minx)/(maxx-minx||1)*96+2).toFixed(1)},${(60-((y-miny)/(maxy-miny||1)*58)).toFixed(1)}`).join(' ');svg.querySelector('polyline').setAttribute('points',s)}catch(e){}}
}
function loadLogs(){try{LOGS=JSON.parse(localStorage.getItem('mtbLogs')||'[]')}catch(e){LOGS=[]}renderLogs()}
function renderLogs(){const routes=Object.fromEntries(DATA.map(r=>[r.id,r.name]));$('logs').innerHTML=LOGS.slice().reverse().map((l,i)=>`<div class="log"><b>${esc(l.date)} · ${esc(routes[l.route]||l.route)}</b><span>${esc(l.flow)} · ${esc(l.mud)}</span><p>${esc(l.note)}</p></div>`).join('')||'<p class="meta">Noch keine Fahrt gespeichert.</p>'}
$('logForm').addEventListener('submit',e=>{e.preventDefault();LOGS.push({route:$('logRoute').value,date:$('logDate').value||today(),flow:$('logFlow').value,mud:$('logMud').value,note:$('logNote').value.trim(),saved_at:new Date().toISOString()});localStorage.setItem('mtbLogs',JSON.stringify(LOGS));$('logNote').value='';renderLogs()});
$('exportLogs').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(LOGS,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mtb-fahrtenlogbuch.json';a.click();URL.revokeObjectURL(a.href)});
[q,sort,type,start,batteryLeft,assist].forEach(el=>el.addEventListener('input',render));
fetch('routes.json').then(r=>r.json()).then(d=>{MODEL=d;DATA=d.routes;populate();loadLogs();render();loadWeather()});
