const LABELS={scenery:'Natur',trail:'Trail',low_traffic:'ruhig',emtb_fun:'E-Bike',viewpoints:'Aussicht',loop_quality:'Loop',surface_confidence:'Daten'};
const $=id=>document.getElementById(id);
const asset=p=>String(p||'').startsWith('http')?p:'/ebike/'+String(p||'').replace(/^\//,'');
let DATA=[],MODEL={},WEATHER=null,LOGS=[],FAVS=[],FOCUS=null,MODE='tour';
const q=$('q'),sort=$('sort'),type=$('type'),timeBudget=$('timeBudget'),grid=$('grid'),summary=$('summary'),rail=$('routeRail'),focusEl=$('focusRoute'),batteryLeft=$('batteryLeft'),batteryLeftText=$('batteryLeftText'),assist=$('assist');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(n){return Math.max(0,Math.min(100,Math.round(n)))}
function today(){return new Date().toISOString().slice(0,10)}
function modeLabel(m=MODE){return m==='tour'?'Normales E-Bike':m==='mtb'?'MTB / E-MTB':'Alle Räder'}
function isTour(r){return (r.ride_style||'mtb')==='tour'}
function modeFor(r){return isTour(r)?'tour':'mtb'}
function difficultyWeight(d){const s=String(d||'').toLowerCase();if(s.includes('leicht')&&!s.includes('mittel'))return 1;if(s.includes('mittel')&&!s.includes('schwer'))return 2;if(s.includes('schwer')||s.includes('abenteuer'))return 4;return 3}
function condition(){if(!WEATHER)return {score:60,label:'lädt',cls:'warn',advice:'Wetterdaten werden geladen. Bis dahin neutral bewertet.',short:'lädt'};const rain=WEATHER.rain48,temp=WEATHER.temp,wind=WEATHER.wind;let score=100-rain*9-Math.max(0,wind-25)*1.3+(temp<4?-12:0);score=pct(score);if(score>78)return {score,label:'Sehr gut fahrbar',short:'sehr gut',cls:'good',advice:'Trocken genug für Wald und Radweg.'};if(score>58)return {score,label:'Fahrbar mit Vorsicht',short:'fahrbar',cls:'warn',advice:'Waldpassagen prüfen, Radwege normal gut planbar.'};if(score>38)return {score,label:'Tour statt Trail',short:'Tour',cls:'warn',advice:'Normale E-Bike-Runden bevorzugen; Trails schonen.'};return {score,label:'Trail meiden',short:'meiden',cls:'bad',advice:'Zu nass/kalt/windig – flach, kurz oder verschieben.'}}
async function loadWeather(){try{const url='https://api.open-meteo.com/v1/forecast?latitude=52.1224&longitude=9.3448&hourly=rain&current=temperature_2m,wind_speed_10m&past_days=2&forecast_days=2&timezone=Europe%2FBerlin';const j=await fetch(url).then(r=>r.json());const rain=(j.hourly?.rain||[]).slice(0,48).reduce((a,b)=>a+(Number(b)||0),0);WEATHER={rain48:Math.round(rain*10)/10,temp:Math.round(j.current?.temperature_2m??0),wind:Math.round(j.current?.wind_speed_10m??0)};$('weatherPill').textContent=`${WEATHER.temp}°C · ${WEATHER.rain48}mm/48h · ${WEATHER.wind}km/h`}catch(e){WEATHER={rain48:0,temp:12,wind:10,offline:true};$('weatherPill').textContent='Wetter offline · neutral'}render()}
function durationMax(r){const nums=String(r.duration||'').replace(/,/g,'.').match(/\d+(?:\.\d+)?/g)||[];return nums.length?Number(nums[nums.length-1]):999}
function filteredByMode(all=DATA){return MODE==='all'?all:all.filter(r=>modeFor(r)===MODE)}
function populate(){const current=type.value;const types=[...new Set(filteredByMode().map(r=>r.type))].sort();type.innerHTML='<option value="">Alle Tourarten</option>'+types.map(t=>`<option>${esc(t)}</option>`).join('');if(types.includes(current))type.value=current;$('logRoute').innerHTML=DATA.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('');$('logDate').value=today()}
function batteryStatus(r){const need=r.battery_model?.[assist.value]||50,left=Number(batteryLeft.value),reserve=r.battery_model?.reserve_percent||15,margin=left-need-reserve;return {need,left,margin,label:margin>=20?'locker':margin>=5?'passt':margin>=0?'dünn':'zu knapp',cls:margin>=20?'good':margin>=0?'warn':'bad'}}
function readiness(r){const b=batteryStatus(r),hours=durationMax(r),budget=Number(timeBudget.value),problems=[];if(b.margin<0)problems.push('Akku zu knapp');else if(b.margin<8)problems.push('Akku-Reserve dünn');if(hours>budget)problems.push('Zeitfenster zu lang');let cls=problems.length?problems.some(p=>p.includes('zu knapp'))?'bad':'warn':'good';return {cls,label:problems.length?problems.join(' · '):'',problems}}
function smartScore(r){const c=condition(),b=batteryStatus(r),ready=readiness(r);let s=r.score+(c.score-60)*0.10+Math.min(10,Math.max(-24,b.margin*0.42))+(FAVS.includes(r.id)?2.5:0);if(durationMax(r)>Number(timeBudget.value))s-=18;if(ready.cls==='bad')s-=18;else if(ready.cls==='warn')s-=4;if(MODE==='tour'&&modeFor(r)==='tour')s+=5;if(MODE==='mtb'&&modeFor(r)==='mtb')s+=4;if(modeFor(r)==='tour'&&c.score<60)s+=4;return Math.round(s*10)/10}
function rows(){let rows=filteredByMode();const query=q.value.toLowerCase().trim();if(query)rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query));if(type.value)rows=rows.filter(r=>r.type===type.value);const key=sort.value;rows.sort((a,b)=>key==='smart'?smartScore(b)-smartScore(a):key==='difficulty'?difficultyWeight(a[key])-difficultyWeight(b[key]):(b[key]||0)-(a[key]||0));return rows}
function statusPill(text,cls){return `<span class="pill ${cls||''}">${esc(text)}</span>`}
function readyChip(ready){return ready.label?`<span class="${ready.cls}">${esc(ready.label)}</span>`:''}
function satelliteMap(id,zoom=true){return `<div class="sat-map" data-sat="${esc(id)}" ${zoom?`data-map-zoom="${esc(id)}" role="button" tabindex="0" aria-label="Streckenkarte vergrößern"`:''}><div class="tile-layer"></div><svg class="sat-track" viewBox="0 0 100 62"><polyline class="track-halo" points=""/><polyline class="track-line" points=""/></svg><div class="sat-badge">Karte · Track · Klick zum Vergrößern</div></div>`}
function miniMap(id,cls='card-map'){return `<svg class="${cls}" viewBox="0 0 100 62" data-track="${esc(id)}"><polyline points=""/></svg>`}
function renderModeTabs(){document.querySelectorAll('.mode-tab').forEach(btn=>{btn.classList.toggle('active',btn.dataset.mode===MODE);btn.setAttribute('aria-pressed',btn.dataset.mode===MODE?'true':'false')})}
function renderSummary(rs){const c=condition(),top=rs[0],tourCount=DATA.filter(isTour).length,mtbCount=DATA.length-tourCount;summary.innerHTML=`<article><span>Ansicht</span><b>${esc(modeLabel())}</b></article><article><span>Top jetzt</span><b>${top?esc(top.name):'–'}</b></article><article><span>Treffer</span><b>${rs.length}</b></article><article><span>Routenbestand</span><b>${tourCount} Tour · ${mtbCount} MTB</b></article>`;$('conditionPanel').innerHTML=`<div><strong>Wetterhinweis</strong><p>${esc(c.advice)} ${WEATHER?`Wetter: ${WEATHER.temp}°C, ${WEATHER.rain48} mm Regen/48h, ${WEATHER.wind} km/h Wind.`:''}</p></div><span class="condition-dot ${c.cls}"></span>`}
function renderRecommendation(rs){const r=rs[0];if(!r){$('recommendation').innerHTML='<p>Keine Route für diese Filter. Suchfeld oder Zeitbudget lockern.</p>';return}const b=batteryStatus(r),ready=readiness(r);$('recommendation').innerHTML=`<div class="rec-top"><span>Empfehlung für ${esc(modeLabel())}</span><b>${smartScore(r)}</b></div><h2>${esc(r.name)}</h2><p>${esc(r.best_for)}</p><div class="rec-stats"><span>${esc(r.bike_profile||modeLabel(modeFor(r)))}</span><span>${r.distance_km} km</span><span>${r.elevation_m} hm</span><span>${esc(r.duration)}</span><span class="${b.cls}">${b.need}% Akku · ${esc(b.label)}</span>${ready.label?`<span class="${ready.cls}">${esc(ready.label)}</span>`:''}</div><div class="hero-actions"><a class="primary" href="#routes" data-focus="${esc(r.id)}">Fokus öffnen</a><a class="ghost" href="${esc(asset(r.gpx_file))}" download>GPX</a></div>`}
function railItem(r){const active=r.id===FOCUS?'active':'',fav=FAVS.includes(r.id)?'★':'☆',ready=readiness(r);return `<button class="rail-item ${active}" data-focus="${esc(r.id)}"><span><b>${esc(r.name)}</b><small>${esc(r.bike_profile||modeLabel(modeFor(r)))} · ${r.distance_km} km · ${r.elevation_m} hm</small>${ready.label?`<small class="${ready.cls}">${esc(ready.label)}</small>`:''}</span><em>${smartScore(r)}</em><i data-fav="${esc(r.id)}">${fav}</i></button>`}
function renderRail(rs){$('routeCount').textContent=`${rs.length} Treffer`;rail.innerHTML=rs.map(railItem).join('')||'<p class="muted inset">Keine passende Route.</p>'}
function gallery(r){const imgs=r.gallery||[];if(!imgs.length)return `<div class="empty-gallery">Noch keine Fotos hinterlegt – die Karte ist für diesen Entwurf die Hauptansicht.</div>`;return `<div class="gallery" aria-label="Streckenfotos, horizontal scrollbar">${imgs.map(i=>`<figure><button class="zoom-photo" data-zoom="${esc(i.url)}" data-caption="${esc(i.title)} · ${esc(i.license)}" aria-label="Foto vergrößern: ${esc(i.title)}"><img src="${esc(i.url)}" alt="${esc(i.title)}" loading="lazy"></button><figcaption>${esc(i.title)} · ${esc(i.license)}</figcaption></figure>`).join('')}</div>`}
function renderFocus(rs){if(!FOCUS||!rs.some(r=>r.id===FOCUS))FOCUS=rs[0]?.id;const r=DATA.find(x=>x.id===FOCUS)||rs[0];if(!r){focusEl.innerHTML='<p>Keine Route gefunden.</p>';return}const b=batteryStatus(r),ready=readiness(r),tags=[r.bike_profile||modeLabel(modeFor(r)),r.traffic_profile,r.difficulty,...(r.decision_tags||r.highlights||[])].filter(Boolean);focusEl.innerHTML=`<div class="focus-layout"><div><div class="focus-head"><div><p class="eyebrow">Fokusroute · ${esc(r.status||'Entwurf')}</p><h2>${esc(r.name)}</h2><p>${esc(r.region)} · ${esc(r.start_mode)} · ${esc(r.surface)}</p></div><button class="fav-btn" data-fav="${esc(r.id)}">${FAVS.includes(r.id)?'★ Favorit':'☆ Favorit'}</button></div>${satelliteMap(r.id)}<p class="route-desc">${esc(r.best_for)}</p><div class="tagrow">${tags.slice(0,8).map(h=>statusPill(h,modeFor(r)==='tour'&&String(h).includes('E-Bike')?'good':'')).join('')}</div>${gallery(r)}</div><aside class="focus-side"><div class="metric"><span>Fahrradtyp</span><b>${esc(r.bike_profile||modeLabel(modeFor(r)))}</b></div><div class="metric"><span>Smartscore</span><b>${smartScore(r)}</b></div><div class="metric ${ready.cls}"><span>Akku/Zeit</span><b>${esc(ready.label||'keine Warnung')}</b></div><div class="metric"><span>Distanz / Höhenmeter</span><b>${r.distance_km} km · ${r.elevation_m} hm</b></div><div class="metric"><span>Dauer</span><b>${esc(r.duration)}</b></div><div class="metric ${b.cls}"><span>Akku</span><b>${b.need}% · ${esc(b.label)}</b></div><div class="pack"><b>Hinweis</b><p>${esc(r.route_mode_note||r.maturity||'Vor erster Fahrt feinprüfen.')}</p></div><div class="focus-actions"><a href="${esc(r.planner_link)}" target="_blank" rel="noopener">BRouter</a><a href="${esc(asset(r.gpx_file))}" download>GPX</a><a href="${esc(r.navigation_link)}" target="_blank" rel="noopener">Navigation</a></div></aside></div><details><summary>Risiken, Score und nächste Schritte</summary><p><b>Check:</b> ${esc((r.risk_notes||[]).join(' · '))}</p><p><b>Track:</b> ${esc(r.track_source)} · <b>Untergrund:</b> ${esc(r.surface)}</p><p>${esc(r.photo_note||'')}</p><div class="scorebars">${Object.entries(r.scores||{}).map(([k,v])=>`<div class="scorebar"><span>${LABELS[k]||k}</span><div class="track"><div class="fill" style="width:${pct(v)}%"></div></div><b>${v}</b></div>`).join('')}</div></details>`;hydrateMaps();hydrateSatellite()}
function card(r){const b=batteryStatus(r),ready=readiness(r),hero=(r.gallery||[])[0];return `<article class="route-card"><div class="card-head"><div><h3>${esc(r.name)}</h3><small>${esc(r.bike_profile||modeLabel(modeFor(r)))} · ${esc(r.type)}</small></div><button data-fav="${esc(r.id)}" aria-label="Favorit umschalten">${FAVS.includes(r.id)?'★':'☆'}</button></div>${hero?`<img class="card-photo" src="${esc(hero.url)}" alt="${esc(hero.title)}" loading="lazy">`:miniMap(r.id)}<div class="mini-stats"><span>${r.distance_km} km</span><span>${r.elevation_m} hm</span><span class="${b.cls}">${b.need}% Akku</span>${ready.label?`<span class="${ready.cls}">${esc(ready.label)}</span>`:''}</div><p>${esc(r.best_for)}</p><button class="open-focus" data-focus="${esc(r.id)}">Details öffnen</button></article>`}
function renderCards(rs){grid.innerHTML=rs.map(card).join('')||'<p class="muted">Keine Karten für diese Filter.</p>'}
function renderCompare(rs){$('compareTable').innerHTML=`<table><thead><tr><th>Route</th><th>Typ</th><th>Score</th><th>Zeit</th><th>km / hm</th><th>Akku</th><th>Status</th><th>Aktion</th></tr></thead><tbody>${rs.map(r=>{const b=batteryStatus(r),ready=readiness(r);return `<tr><td><strong>${esc(r.name)}</strong><small>${esc(r.surface)}</small></td><td>${esc(r.bike_profile||modeLabel(modeFor(r)))}</td><td>${smartScore(r)}</td><td>${esc(r.duration)}</td><td>${r.distance_km} km<br>${r.elevation_m} hm</td><td class="${b.cls}">${b.need}% · ${esc(b.label)}</td><td class="${ready.cls}">${esc(ready.label||'–')}</td><td><a href="${esc(asset(r.gpx_file))}" download>GPX</a></td></tr>`}).join('')}</tbody></table>`}
function render(){batteryLeftText.textContent=batteryLeft.value+'%';renderModeTabs();const rs=rows();renderSummary(rs);renderRecommendation(rs);renderRail(rs);renderFocus(rs);renderCards(rs);renderCompare(rs);hydrateMaps()}
async function hydrateMaps(){for(const svg of document.querySelectorAll('svg[data-track]')){if(svg.dataset.ready)continue;const r=DATA.find(x=>x.id===svg.dataset.track);if(!r?.track_geojson_file)continue;try{const gj=await fetch(asset(r.track_geojson_file)).then(x=>x.json());const pts=gj.features[0].geometry.coordinates.map(c=>[c[0],c[1]]),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys);svg.querySelector('polyline').setAttribute('points',pts.map(([x,y])=>`${((x-minx)/(maxx-minx||1)*96+2).toFixed(1)},${(60-((y-miny)/(maxy-miny||1)*58)).toFixed(1)}`).join(' '));svg.dataset.ready='1'}catch(e){}}}
function lon2tile(lon,z){return Math.floor((lon+180)/360*Math.pow(2,z))}function lat2tile(lat,z){const r=lat*Math.PI/180;return Math.floor((1-Math.log(Math.tan(r)+1/Math.cos(r))/Math.PI)/2*Math.pow(2,z))}function project(lon,lat,z){const n=Math.pow(2,z),x=(lon+180)/360*n*256,r=lat*Math.PI/180,y=(1-Math.log(Math.tan(r)+1/Math.cos(r))/Math.PI)/2*n*256;return [x,y]}
async function hydrateSatellite(){for(const el of document.querySelectorAll('.sat-map')){if(el.dataset.ready)continue;const r=DATA.find(x=>x.id===el.dataset.sat);if(!r?.track_geojson_file)continue;try{const gj=await fetch(asset(r.track_geojson_file)).then(x=>x.json());const pts=gj.features[0].geometry.coordinates.map(c=>[c[0],c[1]]),lons=pts.map(p=>p[0]),lats=pts.map(p=>p[1]);let z=(Math.max(...lons)-Math.min(...lons)>0.12||Math.max(...lats)-Math.min(...lats)>0.08)?12:13;let x1=lon2tile(Math.min(...lons),z),x2=lon2tile(Math.max(...lons),z),y1=lat2tile(Math.max(...lats),z),y2=lat2tile(Math.min(...lats),z);if((x2-x1+1)*(y2-y1+1)>18){z=12;x1=lon2tile(Math.min(...lons),z);x2=lon2tile(Math.max(...lons),z);y1=lat2tile(Math.max(...lats),z);y2=lat2tile(Math.min(...lats),z)}const layer=el.querySelector('.tile-layer'),svg=el.querySelector('.sat-track'),w=(x2-x1+1)*256,h=(y2-y1+1)*256;layer.innerHTML='';layer.style.width=w+'px';layer.style.height=h+'px';svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.style.width=w+'px';svg.style.height=h+'px';const scale=Math.min(el.clientWidth/w,el.clientHeight/h)*0.98;const tx='translate(-50%,-50%) scale('+scale+')';layer.style.transform=tx;svg.style.transform=tx;for(let x=x1;x<=x2;x++)for(let y=y1;y<=y2;y++){const img=document.createElement('img');img.src=`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${y}/${x}`;img.className='sat-tile';img.alt='';img.style.left=((x-x1)*256)+'px';img.style.top=((y-y1)*256)+'px';layer.appendChild(img)}const px=pts.map(([lon,lat])=>{const [x,y]=project(lon,lat,z);return `${x-x1*256},${y-y1*256}`}).join(' ');svg.querySelectorAll('polyline').forEach(p=>p.setAttribute('points',px));el.dataset.ready='1'}catch(e){}}}
function loadLogs(){try{LOGS=JSON.parse(localStorage.getItem('mtbLogs')||'[]');FAVS=JSON.parse(localStorage.getItem('mtbFavs')||'[]')}catch(e){LOGS=[];FAVS=[]}renderLogs()}
function saveFavs(){localStorage.setItem('mtbFavs',JSON.stringify(FAVS))}
function toggleFav(id){FAVS=FAVS.includes(id)?FAVS.filter(x=>x!==id):[...FAVS,id];saveFavs();render()}
function renderLogs(){const routes=Object.fromEntries(DATA.map(r=>[r.id,r.name]));$('logs').innerHTML=LOGS.slice().reverse().map(l=>`<div class="log"><b>${esc(l.date)} · ${esc(routes[l.route]||l.route)}</b><span>${esc(l.flow)} · ${esc(l.mud)}</span><p>${esc(l.note)}</p></div>`).join('')||'<p class="muted">Noch keine Fahrt gespeichert.</p>'}
$('logForm').addEventListener('submit',e=>{e.preventDefault();LOGS.push({route:$('logRoute').value,date:$('logDate').value||today(),flow:$('logFlow').value,mud:$('logMud').value,note:$('logNote').value.trim(),saved_at:new Date().toISOString()});localStorage.setItem('mtbLogs',JSON.stringify(LOGS));$('logNote').value='';renderLogs()});
$('exportLogs').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(LOGS,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ebike-fahrtenlogbuch.json';a.click();URL.revokeObjectURL(a.href)});
document.addEventListener('click',e=>{const mode=e.target.closest('.mode-tab');if(mode){MODE=mode.dataset.mode;populate();FOCUS=null;render();return}const m=e.target.closest('[data-map-zoom]');if(m){e.preventDefault();openMapLightbox(m.dataset.mapZoom);return}const z=e.target.closest('[data-zoom]');if(z){e.preventDefault();openLightbox(z.dataset.zoom,z.dataset.caption||'');return}const close=e.target.closest('[data-lightbox-close]');if(close||e.target.classList?.contains('lightbox')||e.target.classList?.contains('map-lightbox')){closeLightbox();closeMapLightbox();return}const fav=e.target.closest('[data-fav]');if(fav){e.preventDefault();toggleFav(fav.dataset.fav);return}const f=e.target.closest('[data-focus]');if(f){FOCUS=f.dataset.focus;render();document.getElementById('routes').scrollIntoView({behavior:'smooth'});}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLightbox();closeMapLightbox()}if((e.key==='Enter'||e.key===' ')&&document.activeElement?.matches?.('[data-map-zoom]')){e.preventDefault();openMapLightbox(document.activeElement.dataset.mapZoom)}});
function openMapLightbox(id){const r=DATA.find(x=>x.id===id);let box=document.querySelector('.map-lightbox');if(!box){box=document.createElement('div');box.className='map-lightbox';box.innerHTML='<div class="map-lightbox-panel"><button data-lightbox-close aria-label="Karte schließen">×</button><div class="map-lightbox-head"></div><div class="map-lightbox-stage"></div></div>';document.body.appendChild(box)}box.querySelector('.map-lightbox-head').textContent=r?`${r.name} · ${r.distance_km} km · ${r.elevation_m} hm · ${r.bike_profile||modeLabel(modeFor(r))}`:'Streckenkarte';box.querySelector('.map-lightbox-stage').innerHTML=satelliteMap(id,false);box.classList.add('open');hydrateSatellite()}
function closeMapLightbox(){document.querySelector('.map-lightbox')?.classList.remove('open')}
function openLightbox(src,caption){let box=document.querySelector('.lightbox');if(!box){box=document.createElement('div');box.className='lightbox';box.innerHTML='<div class="lightbox-panel"><button data-lightbox-close aria-label="Foto schließen">×</button><img alt=""><p></p></div>';document.body.appendChild(box)}box.querySelector('img').src=src;box.querySelector('p').textContent=caption;box.classList.add('open')}
function closeLightbox(){document.querySelector('.lightbox')?.classList.remove('open')}
[q,sort,type,timeBudget,batteryLeft,assist].forEach(el=>el.addEventListener('input',render));
fetch(asset('routes.json?v=20260601-04'),{cache:'no-store'}).then(r=>r.json()).then(d=>{MODEL=d;DATA=d.routes;populate();loadLogs();FOCUS=rows()[0]?.id;render();loadWeather()});
